### ISSUE TITLE
Any possibility of adding LIN ADV 1.5 to this fork?

### ISSUE THREAD

**Issue by CacikeOtoao** [baloan/Prusa-Firmware#1]
Hi,
Thank you for adding PINDA 2 functionality. Is there a way to add Linear Advance 1.5 also? I think it would complete this firmware.

**Comment by baloan** [comment]
I fear the Linear Advance 1.5 - being a i3 Mk3 feature - depends on the EINSY RAMBo motherboard with Trinamic drivers. I don't think the i3 Mk2 RAMBo mini motherboard supports Linear Advance.

**Comment by baloan** [comment]
I fear Linear Advance 1.5 is not compatible with the i3 Mk2S. The latest firmware for the Mk2S is version 3.2.3. "Starting with firmware 3.9.0, the Original Prusa MK3S features Linear Advance 1.5" (https://help.prusa3d.com/en/article/linear-advance_2252). There is a comment though, "Relevant for should also include MK2S if v3.1.0 firmware, correct?". I am not sure about the impact, maybe it is because the article talks about backwards compatibility to "Linear Advance 1.0". Requires further research.

**Comment by Moorviper** [comment]
btw there is a 3.9.0 fork for the MK2 already https://github.com/cimoalpacino/Prusa-Firmware/tree/MK2S_3.9.0_RAMPS

**Comment by baloan** [comment]
Above fork uses a RAMPS board with A4988 drivers. The original Mk2/S uses the RAMBo mini (Atmega 2560) with 4982 drivers, the Mk3S uses the Einsy RAMBo (Atmega 2560) with TMC2130 drivers. I have no idea about hardware requirements for the Linear Advance 1.5 feature, i.e. whether the RAMBo mini is hardware capable to implement that feature.

**Comment by CacikeOtoao** [comment]
Hi @baloan , thanks for replying. LA 1.5 is/should be fully compatible with MK2S and any other board for that matter, there is already a port of it here https://github.com/Sebastianv650/Prusa-Firmware/tree/MK2_LA_1.5. My idea was to have a version for MK2S that incorporates LA1.5 and PINDAV2 since that is probably the most important features while keeping most of the machine intact. I do have a couple of MK3's and MK2.5's alongside my MK2S and I have to say that the MK2S prints much better with less artifacts. Hence why I will like to keep it as close to stock as possible, I also integrated TMC's 2209 drivers to X and Y through an external board so now is quiter than the MK3S. My coding skills are lacking and that is why I suggest it to you:)

**Comment by CacikeOtoao** [comment]
> btw there is a 3.9.0 fork for the MK2 already https://github.com/cimoalpacino/Prusa-Firmware/tree/MK2S_3.9.0_RAMPS

@ Moorviper I will like to keep most of the stock hardware of the MK2S. I think that fork is much better suited for a scratch build.

**Comment by Moorviper** [comment]
ah when you use a mini rambo it should work with the normal prusa fw.
Normally just adding the mesh level points for the mk42 should do it.

**Comment by Jacada6** [comment]
> ah when you use a mini rambo it should work with the normal prusa fw.
> Normally just adding the mesh level points for the mk42 should do it.

And how can you achieve that exactly? I am trying to do just the opposite. I have an MK2S with an mk52 bed and a pindaV2. I'm trying to get into coding a custom firmware but it's so intimidating everytime i see how many commits mk2s firmware is behind. My printer has been laying for over a year now... How does one modify/merge the parts of the firmware between mk2s and mk2.5/3/s?

**Comment by baloan** [comment]
@CacikeOtoao "Linear Advance (LA) is a technology that predicts the pressure build-up in the extruder when printing at higher speeds. The firmware of the printer uses that prediction to decrease the amount of filament extruded just before stopping and decelerating, which *prevents blobs or artifacts at the sharp corners*." Do you have issues with your printer, like blobs or artifacts at corners? I don't - but then I run my MK2S/PINDAv2 at Slicer default speeds. What kind of benefits do you expect from a LA1.5 backport for your MK2S?

**Comment by Moorviper** [comment]
Jacada6 when you have a mk52 and an pindaV2 you should be able to use the stock prusa Firmware.
You only have to modify the e steps for the extruder because you don't have the bondtech gears and disable the runout sensor in firmware.

**Comment by Jacada6** [comment]
> Jacada6 when you have a mk52 and an pindaV2 you should be able to use the stock prusa Firmware.
> You only have to modify the e steps for the extruder because you don't have the bondtech gears and disable the runout sensor in firmware.

So I can use the latest MK2.5 firmware for my MK2S am i right? I think you can basically disable the runout sensor in the settings. But what exactly do I have to change in the source code for the e-steps? I think I remember seeing values for e-steps but I don’t wanna make a mistake.

Also, I don’t have the new noctua fan, I have the previous stock one. Would the new firmware work fine without the RPM data? I feel like some things may not work correctly if they use RPM data in some functions, do they? Do I have to modify something for that as well?

**Comment by Moorviper** [comment]
You can also disable the fancheck in the firmware or the men.
Then the "broken" fan is ignored.
You can set the e steps per change them in firmware or with gcode
`https://marlinfw.org/docs/gcode/M092.html`
